### ISSUE TITLE
How to reverse proxy using nginx?

### ISSUE THREAD

**Issue by nalakawula** [angristan/docker-hastebin#1]
I can open my hastebin webpage, but can not write anything. When save i got "Something went wrong"
Here my docker-compose:
```yaml
version: '2.3'

services:
  hastebin:
    container_name: hastebin
    image: angristan/hastebin:latest
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "5003:7777"
    environment:
     - UID=4242
     - GID=4242
```
My nginx conf:
```
server {
    server_name  sub.domain.tld;
    error_log /var/log/nginx/paste/error.log warn;
    access_log /var/log/nginx/paste/access.log combined;

    location /haste/ {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:5003/;
  }
}
```
when i open sub.domain.tld/haste, hastebin webpage is showup, then i write some text, hit save, and got error "Something went wrong". Thanks
